### ISSUE TITLE
Переименование. 

### ISSUE THREAD

**Issue by KaZoober** [diman321/PolicyConverter#1]
Добавь в название checkpoint, уверен кому-то да нужен. Я вот написал скрипты для генерации из Excel внутренних команд checkpoint. Теперь возьму твою часть и смогу с мигрировать  с одного сервера на другой :)

**Comment by gam4er** [comment]
Нет, проект мёртв. Да и вряд-ли кому-нибудь нужен - он создавался под
уникальную задачу, использует уникальные БД да и та задача, которую он
решал мертва

6 февраля 2018 г., 13:25 пользователь KaZoober <notifications@github.com>
написал:

**Comment by gam4er** [comment]
Проект не развивается
